### ISSUE TITLE
Google Sheets Script Code

### ISSUE THREAD

**Issue by josemariaaraujo** [DecentLabs/officeAir#1]
Just found your project in Hackaday! Great work!!!

Would you consider adding the google sheets script code to the Git as a file? 
It should help others create new sheets instead of having to copy the original, and it also helps if it stops being available in the future. That way all the code will be in the Git.

Thank you!

**Comment by zodoczi** [comment]
Thanks! :) 
sure, done: https://github.com/DecentLabs/officeAir/blob/master/code.gs
